# -*- coding: utf-8 -*-
"""Assignment 1.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1NDjiCCK760ujIWWEX_gCv-c1aR1LBR98
"""

#1 Simple Calculator
a,b=10,5
print (a+b)
print (a-b)
print (a*b)
print (a**b)
print (a/b)
print (a//b)
print (a%b)

#2 SI
 
P=float (input ("enter value of principal "))
T=float (input ("enter value of time "))
R=float (input ("enter value of rate of interest "))
SI=(P*T*R)/100
print ("SI is:",SI)

#3 Area of Circle
 
r=float (input ("enter radius "))
Area=3.142*r**2
print ('Area of Circle',Area)

#4 Area of Triangle
 
a=float (input('enter 1st side of Triangle '))
b=float (input('enter 2nd side of Triangle '))
c=float (input("enter 3rd side of Triangle "))
s=(a+b+c)/2
Area=(s-a)*(s-b)*(s-c)**0.5
print ("Area of Triangle", Area)

#6 Area of Rectangle
 
l=float (input ("enter the length of Rectangle "))
b=float (input ("enter the breadth of Rectangle "))
a=l*b
print ("Area of Rectangle is:",a)

#5 Celsius to Fahrenheit
 
C=float (input ("enter value of Celsius "))
F=(C*9/5)+32
print ("Temperature in Fahrenheit is :",F)

#7 Perimeter of Square
 
s=float (input ("enter the side of a Square "))
a=4*s
print ("Perimeter of Square is", a)

#8 Circumference of Circle
r=float (input ("enter the value radius"))
a=3.142*2*r
print ("Circumference of Circle:",r)

#9 Swapping of 2 numbers
 
a=int(input ("enter the value of a "))
b=int(input ("enter the value of b "))
temp,a=a,b
b=temp
print ("value of a after swapping:",a)
print ("value of b after swapping:",b)